package com.vandream.mall.commons.constant;


/**
 * @Author Oakley(fangchao)
 * @Date 2018-01-23 13:12
 */

public enum ResultStatusConstant {


    /**
     * 系统级异常
     */
    SUCCESS("OK", 200, "返回正确结果"),
    SERVICE_NOT_FOUND("SERVICE_NOT_FOUND", 400, "服务找不到"),
    METHOD_NOT_FOUND("METHOD_NOT_FOUND", 404, "方法找不到"),
    BAD_REQUEST("BAD REQUEST", 415, "错误请求"),
    SERVER_ERROR("SERVER_ERROR", 500, "服务错误"),
    INPUT_PARAM_ERROR("INPUT_PARAM_ERROR", 600, "参数校验未通过"),
    VERIFY_JIGSAW_FAILED("VERIFY_JIGSAW_FAILED", 777, "拼图校验未通过"),
    BUSINESS_ID_IS_EMPTY("BUSINESS_ID_IS_EMPTY", 778, "业务ID为空"),
    SERVER_DATA_ERROR("SERVER_DATA_ERROR", 800, "服务器数据错误"),
    UPLOAD_FILE_FAILED("UPLOAD_FILE_FAILED", 801, "文件上传失败"),
    REMOTE_INTERFACE_CALL_FAILURE("REMOTE_INTERFACE_CALL_FAILURE", 900, "远程接口调用失败"),
    PARAM_FORMAT_FAILURE("PARAM_FORMAT_FAILURE", 909, "参数转换错误"),

    /**
     * 业务异常
     */

    VERIFY_CODE_ERROR("VERIFY_CODE_ERROR", 10101, "验证码错误"),
    VERIFY_CODE_NOT_NULL("VERIFY_CODE_NOT_NULL", 10102, "验证码不能为空"),
    USER_OR_PASSWORD_NULL("USER_OR_PASSWORD_NULL", 10104, "用户名或密码不可为空"),
    USER_OR_PASSWORD_ERROR("USER_OR_PASSWORD_ERROR", 10105, "用户名或密码错误"),
    LOGIN_TIME_EXPIRE("LOGIN_TIME_EXPIRE", 10106, "当前用户登录时间已过期"),
    TOKEN_NULL("TOKEN_NULL", 10107, "当前用户没有token"),
    DATA_READ_FAIL("DATA_EAD_FAIL", 10108, "读取数据失败"),
    USER_NOT_FOUND("USER_NOT_FOUND", 10109, "用户查询不到"),
    CITY_LIST_ERROR("CITY_LIST_ERROR", 10110, "获取省市区失败"),
    USERID_CAN_NOT_NULL("USERID_CAN_NOT_NULL", 10111, "用户id为空"),
    DATA_LACK_REQUIRED("DATA_LACK_REQUIRED", 10112, "数据异常,缺失必须的数据"),
    DATA_NOT_FOUND("DATA_NOT_FOUND", 10113, "数据异常,数据未找到!"),


    /**
     * 日志异常
     */
    LOG_ACCESS_FAIL("LOG_ACCESS_FAIL", 10450, "日志获取失败！"),
    LOG_INSERT_ERROR("LOG_INSERT_ERROR", 10451, "日志插入失败！"),

    /**
     * 搜索异常
     */
    SEARCH_PARAM_ERROR("SEARCH_PARAM_ERROR", 20201, "搜索参数异常"),
    /**
     * 采购清单-购物车操作异常
     */
    CART_PARAM_CAN_NOT_NULL("CART_PARAM_CAN_NOT_NULL", 20401, "购物车参数不能为空!"),
    CART_INSERT_ERROR("CART_INSERT_ERROR", 20402, "添加收藏商品到购物车异常!"),
    CART_REMOVE_ERROR("CART_REMOVE_ERROR", 20403, "购物车移除商品异常!"),
    CART_READ_LIST_ERROR("CART_READ_LIST_ERROR", 20404, "购物车商品列表读取异常!"),
    CART_MODIFY_ERROR("CART_MODIFY_ERROR", 20405, "修改购物车内商品数量异常!"),
    CART_MODIFY_CART_NUM_ERROR("CART_MODIFY_CART_NUM_ERROR", 20406, "购物车内商品数量不能小于最小起定量!"),
    CART_ITEM_CAN_NOT_FOUND("CART_ITEM_CAN_NOT_FOUND", 20407, "商品查询不到!"),
    CART_INFO_READ_ERROR("CART_INFO_READ_ERROR", 20408, "商品信息读取异常!"),
    CART_GOODS_CAN_NOT_NULL("CART_GOODS_CAN_NOT_NULL", 20409, "购物车商品不能为空!"),
    CART_GOODS_ALREADY_EXISTS("CART_GOODS_ALREADY_EXISTS", 20410, "购物车已存在此商品!"),
    CART_GOODS_NUMBER_IS_BEYOND_THE_MAX_LIMIT("CART_GOODS_NUMBER_IS_BEYOND_THE_MAX_LIMIT", 20411, "购物车商品数量超出最大限制!"),
    CART_THE_QUANTITY_OF_GOODS_CANNOT_BE_DECIMAL("CART_THE_QUANTITY_OF_GOODS_CANNOT_BE_DECIMAL", 20412, "购物车商品数量不能为小数!"),
    CART_THE_QUANTITY_OF_GOODS_CANNOT_BE_ZERO("CART_THE_QUANTITY_OF_GOODS_CANNOT_BE_ZERO", 20413, "购物车商品数量不能小于1!"),
    /**
     * 短信验证-操作异常
     */
    SMS_MESSAGE_PHONE_CAN_NOT_NULL("SMS_MESSAGE_PARAM_CAN_NOT_NULL", 2001, "手机号不能为空!"),
    SMS_MESSAGE_PHONE_NOT_MATCH("SMS_MESSAGE_PHONE_NOT_MATCH", 2002, "手机号码不匹配!"),
    SMS_MESSAGE_SEND_FAILED("SMS_MESSAGE_SEND_FAILED", 2003, "短信验证码发送失败!"),
    SMS_MESSAGE_SENT_ERROR("SMS_MESSAGE_SENT_ERROR", 2004, "您已发送过短信验证码，请稍后再试!"),
    SMS_MESSAGE_SENT_OFTEN_ERROR("SMS_MESSAGE_SENT_OFTEN_ERROR", 2005, "获取短信验证码过于频繁，请稍后重试!"),
    /**
     * 立即下单
     */
    ADD_ORDER_PARAM_ERROR("ADD_ORDER_PARAM_ERROR", 20501, "下单时异常"),
    ORDER_PARAM_CAN_NOT_NULL("ORDER_PARAM_CAN_NOT_NULL", 20502, "下单异常!参数不能为空!!"),
    ORDER_BATCH_INSERT_ERROR("ORDER_BATCH_INSERT_ERROR", 20503, "批量下单异常!!!"),
    ORDER_NUMBER_LESS_MIN("ORDER_NUMBER_LESS_MIN", 20504, "下单数量小于最小起订量"),
    ORDER_NUMBER_MAXIMUM("ORDER_NUMBER_MAXIMUM", 20505, "大于最大起订量"),
    NO_DECIMAL_INPUT_ALLOWED("NO_DECIMAL_INPUT_ALLOWED", 20506, "不允许输入小数"),
    INFORMATION_CAN_NOT_EMPTY("INFORMATION_CAN_NOT_EMPTY", 20507, "信息不能为空"),
    THE_GOODS_IN_THE_NEXT_SHELF_CAN_NOT_BE_SENT_DOWN("THE_GOODS_IN_THE_NEXT_SHELF_CAN_NOT_BE_SENT_DOWN", 20508, "下架商品不能下单！"),
    ORDER_ITEM_MATCH_PARAM_CAN_NOT_NULL("ORDER_ITEM_MATCH_PARAM_CAN_NOT_NULL", 20509, "商品匹配参数不能为空!!"),
    ORDER_ITEM_MATCH_AREA_CAN_NOT_NULL("ORDER_ITEM_MATCH_AREA_CAN_NOT_NULL", 20510, "匹配区域不能为空!!"),

    /**
     * 收藏列表
     */
    ADD_COLLECTION_ERROR("ADD_COLLECTION_ERROR", 20601, "列表添加收藏"),
    REMOVE_COLLECTION_ERROR("REMOVE_COLLECTION_ERROR", 20602, "列表移除收藏"),
    GET_COLLECTION_LIST_ERROR("GET_COLLECTION_LIST", 20603, "获取收藏列表"),
    FAVORITES_SERVICE_INQUITY_ERROR("FAVORITES_SERVICE_INQUITY_ERROR", 20604, "数据库信息查询错误"),
    ITEMLINEID_INVALID_STATE("ITEMLINEID_INVALID_STATE", 20605, "itemLineId无效状态"),
    ITEM_LINE_INVALID("ITEM_LINE_INVALID", 20606, "商品无供应商"),

    /**
     * 商品详情-获取异常
     */
    GET_ITEM_SKUATTRIBUTE_FAILED("GET_ITEMSKUATTRIBUTE_FAILED", 20102, "获取商品技术参数异常！"),
    GET_ITEM_DETAIL_FAILED("GET_ITEMDETAIL_FAILED", 20104, "获取商品详情描述异常！"),
    SUPPLIER_ID_IS_ERROR("SUPPLIER_ID_IS_ERROR", 20105, "查询供应商异常"),
    ITEM_ID_NON_EXISTENT("ITEM_ID_NON_EXISTENT", 20106, "商品id不存在"),
    GTEATER_MAXIMUM_ORDER_QUANTITY("GTEATER_MAXIMUM_ORDER_QUANTITY", 20107, "数量大于最大起订量"),
    ITEM_LINE_NON_EXISTENT("ITEM_LINE_NON_EXISTENT", 20108, "商品item_line不存在"),
    GET_AREA_RANGE_NAME_ERROR("GET_AREA_RANGE_NAME", 20109, "获取区域模板异常"),
    ITEM_SNAPSHOT_DETAIL_EMPTY("ITEM_SNAPSHOT_DETAIL_EMPTY",20110,"获取商品快照详情为空"),
    SOM_SALES_CONTRACT_HEAD_ID_IS_NULL("SOM_SALES_CONTRACT_HEAD_ID_IS_NULL",20111,"销售订单id为空"),
    /**
     * 商城首页
     */
    CATEGORY_ACCESS_FAIL("CATEGORY_ACCESS_FAIL", 10201, "获取类目信息失败！"),
    SECTION_ACCESS_FAIL("SECTION_ACCESS_FAIL", 10202, "获取版块信息失败！"),
    ADVERTISEMENT_ACCESS_FAIL("ADVERTISEMENT_ACCESS_FAIL", 10203, "获取广告信息失败！"),

    /**
     * 企业信息
     */
    FAIL_TO_GET_COMPANY_TYPE("FAIL_TO_GET_COMPANY_TYPE", 10601, "获取企业类别失败！"),
    INTERNAL_INVOCATION_FAILURE("INTERNAL_INVOCATION_FAILURE", 10602, "内部调用失败！"),
    FAIL_TO_GET_COMPANY_AUTHENTICATION_INFO("FAIL_TO_GET_COMPANY_AUTHENTICATION_INFO", 10401, "获取企业认证信息失败!"),
    FAIL_TO_GET_COMPANY_INFO("FAIL_TO_GET_COMPANY_INFO", 10402, "获取企业信息失败!"),

    /**
     * 账户信息
     */
    OBTAINING_USER_INFORMATION_ERROR("OBTAINING_USER_INFORMATION_ERROR", 13001, "参数不能为空"),
    RETURN_USER_INFORMATION_ERROR("RETURN_USER_INFORMATION_ERROR", 13002, "返回用户信息错误"),
    USERNAME_VERY_CIPHER_INFORMATION_ERROR("USERNAME_VERY_CIPHER_INFORMATION_ERROR", 13003, "用户名和密码错误"),
    USER_AUTHENTICATION_CODE_INFORMATION("USER_AUTHENTICATION_CODE_INFORMATION", 13004, "用户验证码信息异常"),
    USER_PASSWORD_INCONSISTENCY_ERROR("USER_PASSWORD_INCONSISTENCY_ERROR", 13005, "用户密码不一致"),
    USER_VERIFY_CODE_INCONSISTENCY_ERROR("USER_VERIFY_CODE_INCONSISTENCY_ERROR", 13006, "验证码不一致"),
    CALLING_INTERFACE_EXCEPTION("CALLING_INTERFACE_EXCEPTION", 13006, "调用接口内部错误"),
    CREATE_USER_TOKEN_ERROR("CREATE_USER_TOKEN_ERROR", 13007, "生成用户token错误"),

    /**
     * 子账户信息
     */
    UPDATE_SUB_ACCOUNT_ERROR("UPDATE_SUB_ACCOUNT_ERROR", 14000, "修改子账户信息失败"),
    UPDATE_PERMISSION_ERROR("UPDATE_PERMISSION_ERROR", 14001, "修改子账户权限信息失败"),
    FIND_ROLE_AND_MENU_LIST_BY_ID_ERROR("FIND_ROLE_AND_MENU_LIST_BY_ID_ERROR", 14002, "根据账户id查询角色和菜单权限列表异常"),
    FIND_ALL_ROLE_AND_MENU_LIST_ERROR("FIND_ALL_ROLE_AND_MENU_LIST_ERROR", 14003, "查询角色和菜单权限列表异常"),
    INPUT_LENGTH_ERROR("INPUT_LENGTH_ERROR", 14004, "用户名长度错误"),
    PHONE_NUMBER_IS_ALREADY_EXISTS("PHONE_NUMBER_IS_ALREADY_EXISTS", 14005, "手机号已经存在，不能重复添加子账户"),

    /**
     * 收货地址
     */
    GET_ADDRESS_LIST_ERROR("GET_ADDRESS_LIST_ERROR", 15001, "获取地址信息列表异常"),
    GET_ADDRESS_ERROR("GET_ADDRESS_ERROR", 15003, "获取地址信息异常"),
    MODIFY_OR_INSERT_FAILED("MODIFY_OR_INSERT_FAILED", 15005, "新增、修改收货地址异常"),
    DELETE_ADDRESS_FAILED("DELETE_ADDRESS_FAILED", 15008, "删除操作异常"),
    SET_DEFAULT_ADDRESS_FAILED("SET_DEFAULT_ADDRESS_FAILED", 15010, "设置默认地址异常"),
    ADD_ADDRESS_EXCEEDS_LIMIT("ADD_ADDRESS_EXCEEDS LIMIT", 15011, "常用地址最多为20个，如若添加，需删除地址"),
    ADDRESS_LENGTH_TOO_LONG("ADDRESS_LENGTH_TOO_LONG", 15012, "详细地址必须小于100个字符"),
    CONTACT_NAME_LENGTH_TOO_LONG("CONTACT_NAME_LENGTH_TOO_LONG", 15013, "收货人姓名必须小于40个字符"),
    POST_CODE_LENGTH_TOO_LONG("POST_CODE_LENGTH_TOO_LONG", 15014, "区域编码必须小于10个字符"),

    /**
     * Account 用户账户
     */
    ACCOUNT_PHONE_ALREADY_REGISTERED("ACCOUNT_PHONE_ALREADY_REGISTERED", 10001, "该手机号已经被注册!"),
    ACCOUNT_PHONE_EMPTY("ACCOUNT_PHONE_FORMAT_ERROR", 10002, "手机号不能为空!"),
    ACCOUNT_PHONE_FORMAT_ERROR("ACCOUNT_PHONE_FORMAT_ERROR", 10002, "此手机号格式错误!"),
    ACCOUNT_REGISTER_PARAM_ERROR("ACCOUNT_REGISTER_PARAM_ERROR", 10003, "注册参数异常!"),
    ACCOUNT_REGISTER_PASSWORD_DIFFER("ACCOUNT_REGISTER_PASSWORD_DIFFER", 10004, "注册两次密码输入不一致"),
    ACCOUNT_LOGIN_PASSWORD_EMPTY("ACCOUNT_LOGIN_PASSWORD_EMPTY", 10005, "登录密码不能为空"),
    ACCOUNT_LOGIN_PHONE_OR_PASSWORD_EMPTY("ACCOUNT_LOGIN_PHONE_OR_PASSWORD_EMPTY", 10005,
            "手机号或登录密码错误!"),
    ACCOUNT_REGISTER_FAILED("ACCOUNT_REGISTER_FAILED", 10006, "注册失败!"),
    ACCOUNT_REPEAT_SUBMIT_COUNT_EXCEEDS_LIMIT("ACCOUNT_REPEAT_SUBMIT_COUNT_EXCEEDS_LIMIT", 10007,
            "重复提交次数超限!"),

    FAIL_TO_GET_ACCOUNT("FAIL_TO_GET_ACCOUNT", 10008, "查询账户信息失败!"),
    ACCOUNT_NOT_FOUND("ACCOUNT_NOT_FOUND", 10009, "账户信息不存在!"),
    ACCOUNT_STATUS_EXCEPTION("ACCOUNT_STATUS_EXCEPTION", 10010, "账户状态异常!"),
    ACCOUNT_DATA_EXCEPTION("ACCOUNT_STATUS_EXCEPTION", 10011, "账户数据异常!"),
    /**
     * 需求管理中心异常
     */
    ADD_DEMAND_PARAM_CAN_NOT_NULL("ADD_DEMAND_PARAM_CAN_NOT_NULL", 60006, "发布需求参数为空！"),
    DEMAND_PUBLISH_EXCEPTION("DEMAND_PUBLISH_EXCEPTION", 60001, "需求发布异常!"),
    DEMAND_DISCUSS_PARAM_CAN_NOT_NULL("DEMAND_DISCUSS_PARAM_CAN_NOT_NULL", 60007, "发布详细需求参数不能为空"),
    DEMAND_LIST_QUERY_FAILED("DEMAND_LIST_QUERY_FAILED", 60002, "需求列表查询失败!"),
    DEMAND_SOLUTION_PARAM_CAN_NOT_NULL("DEMAND_SOLUTION_PARAM_CAN_NOT_NULL", 60003, "需求派发单参数不能为空!"),
    DEMAND_SOLUTION_LIST_QUERY_FAILED("DEMAND_SOLUTION_LIST_QUERY_FAILED", 60004, "需求派发单列表查询失败!"),
    DEMAND_SOLUTION_STATUS_UPDATE_FAILED("DEMAND_SOLUTION_STATUS_UPDATE_FAILED", 60005, "需求派发单更新失败!"),
    DEMAND_DETAIL_INFO_QUERY_FAILED("DEMAND_DETAIL_INFO_QUERY_FAILED", 60006, "查询需求单详细信息失败"),

    /**
     * 需方合同异常处理
     */
    //Contract parameters are introduced into null
    CONTRACT_PARAMETERS_INTRODUCE_INTO_NULL("CONTRACT_PARAMETERS_INTRODUCE_INTO_NULL", 30301, "参数传入为空"),
    QUERY_DATABASE_ERROR("QUERY_DATABASE_ERROR", 30302, "查询数据库错误"),
    CALL_INTERFACE_RETURN_EXCEPTION("CALL_INTERFACE_RETURN_EXCEPTION", 30303, "用户调用接口异常"),
    INVOICE_QUANTITY_ABNORMAL("INVOICE_QUANTITY_ABNORMAL",30304,"签收量必须小于等于实发量"),

    /**
     * 发货订单详情异常
     **/
    DELIVERY_INFO_PARAM_IS_NULL_EXCEPTION("DELIVERY_INFO_PARAM_IS_NULL_EXCEPTION", 70001, "发货订单参数不能为空!"),

    /**
     * 发货订单详情数据不正确
     **/
    DELIVERY_INFO_PARAM_SUBMIT_ERROR("DELIVERY_INFO_PARAM_SUBMIT_ERROR", 70100, "提交发货信息数据不正确!"),

    /**
     * 提交发货异常
     **/
    DELIVERY_INFO_SUBMIT_ERROR_EXCEPTION("DELIVERY_INFO_SUBMIT_ERROR_EXCEPTION", 70101, "提交发货信息异常");

    private String status;
    private int code;
    private String desc;

    private ResultStatusConstant(String status, int code, String desc) {
        this.status = status;
        this.code = code;
        this.desc = desc;
    }

    public int getCode() {
        return code;
    }

    public ResultStatusConstant setCode(int code) {
        this.code = code;
        return this;
    }

    public String getDesc() {
        return desc;
    }

    public ResultStatusConstant setDesc(String desc) {
        this.desc = desc;
        return this;
    }

    public String getStatus() {
        return status;
    }

    public ResultStatusConstant setStatus(String status) {
        this.status = status;
        return this;
    }
}